# SonarQube project info
sonar.projectKey=TVM-Asset-Management
sonar.projectName=TVM asset Management

# Source code
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/environments/**

# Language & encoding
sonar.sourceEncoding=UTF-8

# TypeScript config
sonar.typescript.tsconfigPath=tsconfig.json

# SonarQube server
sonar.host.url=http://localhost:9000
